### ISSUE TITLE
Error when exporting a model with painted textures using Embed Image Data

### ISSUE THREAD

**Issue by FLamparski** [Kupoman/blendergltf#22]
Representative traceback:

```
Traceback (most recent call last):
  File "/home/filip/.config/blender/2.76/scripts/addons/blendergltf-master/__init__.py", line 89, in execute
    gltf = blendergltf.export_gltf(scene, settings)
  File "/home/filip/.config/blender/2.76/scripts/addons/blendergltf-master/blendergltf.py", line 1047, in export_gltf
    'images': export_images(settings, scene_delta.get('images', [])),
  File "/home/filip/.config/blender/2.76/scripts/addons/blendergltf-master/blendergltf.py", line 839, in export_images
    return {image.name: export_image(image) for image in images}
  File "/home/filip/.config/blender/2.76/scripts/addons/blendergltf-master/blendergltf.py", line 839, in <dictcomp>
    return {image.name: export_image(image) for image in images}
  File "/home/filip/.config/blender/2.76/scripts/addons/blendergltf-master/blendergltf.py", line 832, in export_image
    uri = image_to_data_uri(image)
  File "/home/filip/.config/blender/2.76/scripts/addons/blendergltf-master/blendergltf.py", line 812, in image_to_data_uri
    for span in range((height - 1) * width_byte_4, -1, - width_byte_4))
ValueError: range() arg 3 must not be zero
```

**Comment by Kupoman** [comment]
Hi FLamparski, thanks for reporting the bug. Do you have an example file that causes this error?
