### ISSUE TITLE
Error exporting Blender file with missing image files

### ISSUE THREAD

**Issue by ghost** [Kupoman/blendergltf#51]
I try to export a Blender model to glTF using this addon. However, the model has a reference to a image file which does not exist any more. I can't seem to easily find out how to remove the missing image either.

Blender version 2.78.

This is the error message:

                                                                                                  Traceback (most recent call last):
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blendergltf-master\__init__.py", line 131, in execute
    gltf = blendergltf.export_gltf(scene, settings)
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blendergltf-master\blendergltf.py", line 1207, in export_gltf
    'images': export_images(settings, scene_delta.get('images', [])),
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blendergltf-master\blendergltf.py", line 989, in export_images
    return {'image_' + image.name: export_image(image) for image in images if check_image(image)}
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blendergltf-master\blendergltf.py", line 989, in <dictcomp>
    return {'image_' + image.name: export_image(image) for image in images if check_image(image)}
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blendergltf-master\blendergltf.py", line 956, in check_image
    errors.add('x dimension is 0')
AttributeError: 'list' object has no attribute 'add'

**Comment by stevenvergenz** [comment]
This is addressed in PR #52

**Comment by Kupoman** [comment]
Merged #52.
