### ISSUE TITLE
activating addon causes error

### ISSUE THREAD

**Issue by freder** [Kupoman/blendergltf#54]
hi,

when I try to active the addon, I get this error:

```
Traceback (most recent call last):
  File "/private/var/folders/3g/5hppblhd2pzdxhvjt8tj5_z00000gn/T/AppTranslocation/0AEC2418-2E78-40E2-92CD-7E92AB860044/d/blender.app/Contents/MacOS/../Resources/2.78/scripts/modules/addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "/Users/freder/Library/Application Support/Blender/2.78/scripts/addons/blendergltf-master/__init__.py", line 43, in <module>
    from . import blendergltf
  File "/Users/freder/Library/Application Support/Blender/2.78/scripts/addons/blendergltf-master/blendergltf.py", line 1019
    else if texture.image.channels not in [3,4]:
          ^
SyntaxError: invalid syntax
```

**Comment by stevenvergenz** [comment]
Oh, my bad! I'm used to javascript lol. PR incoming.
