### ISSUE TITLE
Error when exporting a model with vertex group not related to bone

### ISSUE THREAD

**Issue by vcasagrande** [Kupoman/blendergltf#71]
When I try to export the model with the vertex group, Blender shows the following error:

![2017-03-11_20-08-13](https://cloud.githubusercontent.com/assets/5779505/23827664/06d3002c-0697-11e7-93f1-85f27bcae12e.gif)

```
Traceback (most recent call last):
  File "C:\Users\victo\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blendergltf-master\__init__.py", line 177, in execute
    gltf = export_gltf(data, settings)
  File "C:\Users\victo\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blendergltf-master\blendergltf.py", line 1403, in export_gltf
    'skins': export_skins(state),
  File "C:\Users\victo\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blendergltf-master\blendergltf.py", line 850, in export_skins
    for mesh_name, obj in state['skinned_meshes'].items()
  File "C:\Users\victo\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blendergltf-master\blendergltf.py", line 850, in <dictcomp>
    for mesh_name, obj in state['skinned_meshes'].items()
  File "C:\Users\victo\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\blendergltf-master\blendergltf.py", line 838, in export_skin
    bone = arm.data.bones[group.name]
KeyError: 'bpy_prop_collection[key]: key "hair" not found'

location: <unknown location>:-1
```

Also, thank you for the Blender add-on.

**Comment by Kupoman** [comment]
If you can supply a .blend file that reproduces the problem, it will help a lot in resolving the bug.

**Comment by afvc** [comment]
i'm having the same problem, did u manage to solve it?

**Comment by vcasagrande** [comment]
I was using another format before the fix, @afvc did you try with the latest release?
