### ISSUE TITLE
Error exporting modular animated mesh: `line 1403, in export_gltf     'skins': export_skins(state)`

### ISSUE THREAD

**Issue by kevzettler** [Kupoman/blendergltf#72]
```
^[read blend: /Users/kev/code/robotbones/assets/models/mechsniper/blender/qubicle/rig-bones-mirrored.blend
Traceback (most recent call last):
  File "/Users/kev/Library/Application Support/Blender/2.78/scripts/addons/blendergltf/__init__.py", line 177, in execute
    gltf = export_gltf(data, settings)
  File "/Users/kev/Library/Application Support/Blender/2.78/scripts/addons/blendergltf/blendergltf.py", line 1403, in export_gltf
    'skins': export_skins(state),
  File "/Users/kev/Library/Application Support/Blender/2.78/scripts/addons/blendergltf/blendergltf.py", line 850, in export_skins
    for mesh_name, obj in state['skinned_meshes'].items()
  File "/Users/kev/Library/Application Support/Blender/2.78/scripts/addons/blendergltf/blendergltf.py", line 850, in <dictcomp>
    for mesh_name, obj in state['skinned_meshes'].items()
  File "/Users/kev/Library/Application Support/Blender/2.78/scripts/addons/blendergltf/blendergltf.py", line 838, in export_skin
    bone = arm.data.bones[group.name]
KeyError: 'bpy_prop_collection[key]: key "Group" not found'

location: <unknown location>:-1
```

**Comment by Moguri** [comment]
Can you provide a simple blend file that demonstrates this problem?

**Comment by kevzettler** [comment]
http://kevzettler.com/robotbones/assets/models/mechsniper/blender/qubicle/rig-bones-mirrored.blend
